---
title: "Creating CSV"
author: "Team SIM"
date: "2023-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)

```


```{r}
# # Set the path to the folder containing the CSV files
# csv_folder <- "~/Desktop/Intro to Data Science/final project CaBi/cabi all csv/csv/1 set"
# 
# # Get a list of all CSV files in the folder
# csv_files <- list.files(path = csv_folder, pattern = "*.csv", full.names = TRUE)
# 
# # Initialize an empty list to store the data frames
# csv_list <- list()
# 
# # Loop through each CSV file and read it into a data frame
# for (i in 1:length(csv_files)) {
#   csv_list[[i]] <- read.csv(csv_files[i], header = TRUE)
# }
# 
# # Merge all the data frames into one
# merged_csv1 <- do.call(rbind, csv_list)

```


```{r}
# merged_csv1 <- merged_csv1[c(1,2,4,5,8,9)]
# write.csv(merged_csv1,file = "merged_csv1.csv",row.names = F)

```


```{r}
# Reads a CSV file and creates a data frame in R.
CaBi1 <- read.csv("merged_csv1.csv")
# Result:The CSV file merged_csv1.csv is read and stored as a data frame named CaBi1 in the R environment.
```

```{r}
# Shows the first few rows of the data frame CaBi1.
head(CaBi1)
# Result:Displays the first 6 rows of the data frame CaBi1, giving a glimpse of its contents.
```

```{r}
# Returns the number of rows in the data frame CaBi1.
nrow(CaBi1)
# Result: Returns the number of rows in the data frame CaBi1. This number represents the total number of observations in the data set.
```


```{r}
CaBi1 <- CaBi1 %>% select(-Start.station.number)
CaBi1 <- CaBi1 %>% select(-Bike.number)
unique(CaBi1$Member.type)
```

```{r}
#for Hourly
CaBi1$Start.date <- strptime(CaBi1$Start.date,format="%Y-%m-%d %H:%M:%S",tz = "EST")

CaBi1$Start.date <- format(round(CaBi1$Start.date, units="hours"), format="%Y-%m-%d %H:%M:%S")
```


```{r}
#For day wise
CaBi1$Start.date <- strptime(CaBi1$Start.date,format="%Y-%m-%d",tz = "EST")
```

```{r}
CaBi1 <- CaBi1 %>% 
  group_by(Start.date, Start.station) %>% 
  mutate(noofBikes = n(), 
         Duration = mean(Duration, na.rm = TRUE)) %>% 
  distinct(Start.date, Start.station, .keep_all = TRUE) %>% 
  arrange(Start.date,Start.station)
```


```{r}
head(CaBi1)
```


```{r}
# for hours
write.csv(CaBi1,file = "CaBi1hour.csv",row.names = F)
```


```{r}
# for days
write.csv(CaBi1,file = "CaBi1days.csv",row.names = F)
```


```{r}
# # Set the path to the folder containing the CSV files
# csv_folder <- "~/Desktop/Intro to Data Science/final project CaBi/cabi all csv/csv/2 set"
# 
# # Get a list of all CSV files in the folder
# csv_files <- list.files(path = csv_folder, pattern = "*.csv", full.names = TRUE)
# 
# # Initialize an empty list to store the data frames
# csv_list <- list()
# 
# # Loop through each CSV file and read it into a data frame
# for (i in 1:length(csv_files)) {
#   csv_list[[i]] <- read.csv(csv_files[i], header = TRUE)
# }
# 
# # Merge all the data frames into one
# merged_csv2 <- do.call(rbind, csv_list)

```

```{r}
# head(merged_csv2)
```


```{r}
# print(colSums(is.na(merged_csv2)))

```


```{r}
# merged_csv2 <- merged_csv2[c(3,4,5,7,13)]
```


```{r}
# head(merged_csv2)
# write.csv(merged_csv2,file = "merged_csv2.csv",row.names = F)
```

```{r}
CaBi2 <- read.csv("merged_csv2.csv")
```

```{r}
head(CaBi2)
```

```{r}
summary(CaBi2)
```



```{r}
CaBi2 <- CaBi2 %>% select(-end_station_name)

```


```{r}
CaBi2$Duration <- difftime(CaBi2$ended_at, CaBi2$started_at)

```


```{r}

CaBi2 <- CaBi2 %>% select(-ended_at)
```


```{r}
#for Hourly
CaBi2$started_at <- strptime(CaBi2$started_at,format="%Y-%m-%d %H:%M:%S",tz = "EST")

CaBi2$started_at <- format(round(CaBi2$started_at, units="hours"), format="%Y-%m-%d %H:%M:%S")
```




```{r}
#For day wise
CaBi2$started_at <- strptime(CaBi2$started_at,format="%Y-%m-%d",tz = "EST")

CaBi2$started_at <- format(CaBi2$started_at, "%Y-%m-%d")
```


```{r}
CaBi2$Duration <- as.double(CaBi2$Duration)
```



```{r}
CaBi2 <- CaBi2 %>% 
  group_by(started_at, start_station_name) %>% 
  mutate(noofBikes = n(),
         Duration = mean(Duration, na.rm = TRUE)) %>% 
  distinct(started_at, start_station_name, .keep_all = TRUE) %>% 
  arrange(started_at,start_station_name)
```


```{r}
# for hours
write.csv(CaBi2,file = "CaBi2hour.csv",row.names = F)
```


```{r}
# for days
write.csv(CaBi2,file = "CaBi2days.csv",row.names = F)
```



